FitnessTracker.MVC/FitnessTracker.MVC/Controllers/CompeteController.cs
using FitnessTracker.MVC.Helpers;
using FitnessTracker.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FitnessTracker.MVC.Controllers
{
    public class CompeteController : Controller
    {
        private readonly ILogger<CompeteController> _logger;

        public CompeteController(ILogger<CompeteController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SoccerLovers()
        {
            return View();
        }

        public IActionResult WeightLifters()
        {
            return View();

        }

        public IActionResult OutdoorRunners()
        {
            return View();
        }
        public IActionResult SLGroupStatistics()
        {
            return View();
        }
        public IActionResult wLGroupStatistics()
        {
            return View();
        }
        public IActionResult ORGroupStatistics()
        {
            return View();
        }

        public IActionResult SLSettings()
        {
            return View();
        }

        public IActionResult ORSettings()
        {
            return View();
        }

        public IActionResult WLSettings()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveSoccerLoversSettings()
        {
            TempData["SuccessMessage"] = "Settings successfully saved!";
            return RedirectToAction("SoccerLovers");
        }

        [HttpPost]
        public IActionResult SaveWeightLiftersSettings()
        {
            TempData["SuccessMessage"] = "Settings successfully saved!";
            return RedirectToAction("WeightLifters");
        }

        [HttpPost] 
        public IActionResult SaveOutdoorRunnersSettings()
        {
            TempData["SuccessMessage"] = "Settings successfully saved!";
            return RedirectToAction("OutdoorRunners");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

FitnessTracker.MVC/FitnessTracker.MVC/Controllers/WorkoutController.cs
using FitnessTracker.MVC.Helpers;
using FitnessTracker.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System.Diagnostics;

namespace FitnessTracker.MVC.Controllers
{
    public class WorkoutController : Controller
    {
        private readonly ILogger<WorkoutController> _logger;
        private readonly CacheHelper _cacheHelper;

        public WorkoutController(ILogger<WorkoutController> logger, CacheHelper cacheHelper)
        {
            _logger = logger;
            _cacheHelper = cacheHelper;
        }

        public IActionResult Index()
        {
            List<WorkoutModel> allWorkouts = _cacheHelper.GetMyWorkouts();
            var distinctDates = allWorkouts.Where(w => w.Date.HasValue).Select(x => x.Date.Value).Distinct().OrderBy(d => d).ToList();
            return View(distinctDates);
        }


        public IActionResult AddWorkout()
        {
            return View();
        }

        public IActionResult AddExistingWorkout()
        {
            List<string> lstCategories = _cacheHelper.GetCategories();
            return View(lstCategories);
        }

        public IActionResult ViewWorkoutsForCategory(string category)
        {
            List<WorkoutModel> lstWorkouts = _cacheHelper.GetWorkoutsByCategory(category);
            ViewBag.Category = category;
            return View(lstWorkouts);
        }
        public IActionResult WorkoutDetails(string workoutName, string category)
        {
            WorkoutModel? oWorkout = _cacheHelper.GetWorkoutByNameAndCategory(workoutName, category);
            if (oWorkout != null)
            {
                return View(oWorkout);
            }
            return RedirectToAction("ViewWorkoutsForCategory", new { category = category });
        }

        [HttpPost]
        public IActionResult AddWorkoutToMyWorkouts(string workoutName, string category, DateTime workoutDate)
        {
            _cacheHelper.AddWorkoutToMyWorkouts(workoutName, category, workoutDate);
            TempData["SuccessMessage"] = "Workout successfully saved to my workouts!";
            return RedirectToAction("Index");
        }

        public IActionResult CreateWorkout()
        {
            ViewBag.Categories = _cacheHelper.GetCategories();
            return View(new WorkoutModel());
        }

        [HttpPost]
        public IActionResult RemoveWorkoutFromMyWorkouts(string workoutName, string category, DateTime dDate)
        {
            _cacheHelper.RemoveWorkoutFromMyWorkouts(workoutName, category, dDate);
            TempData["SuccessMessage"] = workoutName + " has been successfully removed from " + dDate.ToString("dddd, MMMM dd") + "!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SaveWorkout(WorkoutModel oWorkout)
        {
            _cacheHelper.AddWorkoutToExistingWorkouts(oWorkout);
            TempData["SuccessMessage"] = "Workout successfully saved to existing workouts!";
            return RedirectToAction("AddWorkout");
        }

        public IActionResult WorkoutsByDate(DateTime date)
        {
            List<WorkoutModel> lstWorkoutsByDate = _cacheHelper.GetMyWorkoutsByDate(date);
            ViewBag.Date = date;
            return View(lstWorkoutsByDate);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult FilterWorkouts()
        {
            ViewBag.Categories = _cacheHelper.GetCategories();
            return View();
        }

        [HttpPost]
        public IActionResult ApplyFilters(string category, DateTime date1, DateTime date2)
        {
            _cacheHelper.ApplyFilters(category, date1, date2);
            TempData["SuccessMessage"] = "Filters applied";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ClearFilters()
        {
            _cacheHelper.ClearFilters();
            TempData["SuccessMessage"] = "Filters cleared";
            return RedirectToAction("Index");
        }
    }
}

FitnessTracker.MVC/FitnessTracker.MVC/Views/Shared/_Layout.cshtml
@{
    string currentController = ViewContext.RouteData.Values["controller"].ToString();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fitness Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FitnessTracker.MVC.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("css", required: false)
</head>
<body>
    <header>
        <div id="navbar" class="navbar fixed-bottom navbar-light bg-light">
            <div class="container">
                <div class="d-flex justify-content-between w-100">
                    <a class="btn d-flex align-items-center" href="@Url.Action("Index", "Home")">
                        <i class="fas fa-home fa-xl @(currentController == "Home" ? "active" : "")"></i>
                    </a>
                    <a class="btn d-flex align-items-center" href="@Url.Action("Index", "Workout")">
                        <i class="fa fa-calendar fa-xl @(currentController == "Workout" ? "active" : "")"></i>
                    </a>
                    <a class="btn d-flex align-items-center" href="@Url.Action("Index", "Compete")">
                        <i class="fa-solid fa-chart-simple fa-xl  @(currentController == "Compete" ? "active" : "")"></i>
                    </a>
                    <!-- We don't need this to link to anything for any of our tasks -->
                    <a href="#" class="btn d-flex align-items-center">
                        <i class="fa fa-user fa-xl"></i>
                    </a>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>